apiVersion: v1
kind: Service
metadata:
  name: {{ include "asset-manager-api.fullname" . }}
  labels:
    {{- include "asset-manager-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}  # 내부 실제 포트 (8080)
      protocol: TCP
      name: http
  selector:
    {{- include "asset-manager-api.selectorLabels" . | nindent 4 }}
